### ISSUE TITLE
使用mxnet载入模型出错。

### ISSUE THREAD

**Issue by ChenjingYu1993** [zuoqing1988/ZQCNN-MTCNN-vs-libfacedetection#7]
左博士，您好，我想尝试一下使用mxnet对您提供的模型进行载入，mxnet版本为1.2.0cpu版本，结果报了个错误：
Traceback (most recent call last):
  File "compile.py", line 10, in <module>
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/model.py", line 419, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 2535, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [03:34:34] src/operator/custom/custom.cc:104: Check failed: CustomOperator::Get()->Find(params.op_type) != nullptr Cannot find custom operator negativemining_onlylandmark106

载入代码如下：
import mxnet as mx
from mxnet import ndarray as nd
 
prefix, epoch = "lnet106-big", 0
sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
image_size = (48, 48)
opt_level = 3
 
shape_dict = {'data':(1, 3, *image_size)}
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(sym, arg_params, aux_params)

您能提供一下帮助吗？谢谢左博啦~

**Comment by ChenjingYu1993** [comment]
问题已经解决~

**Comment by meloncolie** [comment]
@1976277169 哈喽，我也遇到了同样的问题，你是怎么解决的呢？另外我现在的输出不对，你有运行脚本吗？
